- name: install monitoring stack
  hosts: _Name_bastion_instance
  become: yes
  roles:
  - prometheus
  - grafana
  - alertmanager
- name: install node-exporter
  hosts: 
    -_Name_tf_Slave
    -_Name_tf_Master
  become: yes
  roles:
  - node-exporter
